spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 345055583578-a6k6fg3kuf5unhffs5cem4njh165ca6n.apps.googleusercontent.com
            client-secret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

app:
  tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
  tokenExpirationMsec: 864000000
  authorizedRedirectUris:
    http://localhost:3000/oauth2/redirect