# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Write to Application.properties
      uses: christian-draeger/write-properties@1.1.0
      with:
          path: './src/main/resources/application.properties'
          property: |
              'spring.security.oauth2.client.registration.google.client-id'
              'spring.security.oauth2.client.registration.google.client-secret'
              'spring.security.oauth2.client.registration.google.redirectUri'
              'spring.security.oauth2.client.registration.google.scope'
              'app.tokenSecret'
              'app.tokenExpirationMsec'
              'app.authorizedRedirectUris'
          value: |
            ${{secrets.GOOGLE_CLIENT}}
            ${{secrets.GOOGLE_SECRET}} 
            ${{secrets.GOOGLE_REDIRECT}} 
            ${{secrets.GOOGLE_SCOPE}} 
            ${{secrets.APP_TOKEN_SECRET}} 
            ${{secrets.APP_TOKEN_EXPIRATION}} 
            ${{secrets.APP_TOKEN_ALLOWED_REDIRECT}}
    - name: Build with Maven
      run: mvn -B package --file Backend/pom.xml
